version: "3.9"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: laravel-puribunda
    container_name: laravel-puribunda
    restart: unless-stopped
    volumes:
        - ./:/var/www/html
        - ./docker-config/nginx.conf:/etc/nginx/nginx.conf
        - ./docker-config/php.ini:/etc/php8/conf.d/custom.ini
    networks:
        - mainapp
    ports:
        - 9991:8080

networks:
  mainapp:
    name: mainapp